version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
      - codecov/upload:
          when: on_success
workflows:
  main:
    jobs:
      - build:
          context: tokens-chathurabuddi